name: 微博超话签到
on:
  workflow_dispatch:  # 允许手动触发
  schedule: # 每天下午12点执行 时差为 +8
    - cron: '0 04 * * *'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests pytz

      - name: 执行脚本
        env:
          SUB_TOKEN: ${{ secrets.SUB_TOKEN }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          # EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
        run: |
          python weibo/chaohua_dosign.py || echo "Script failed with exit code $?"

      - name: 空提交保持活跃（仅定时触发）
        if: success() && github.event_name == 'schedule'
        run: |
          git config --local user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git remote set-url origin https://${{ github.actor }}:${{ github.token }}@github.com/${{ github.repository }}
          git pull --rebase --autostash
          git commit --allow-empty -m "CHORE: 保持运行.."
          git push

      - name: 清理旧的 Workflow 记录
        if: always()
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 60
